### PR TITLE
upper bound for NNlib

### PR DESCRIPTION
**Pull request by CarloLucibello**
Fix https://github.com/FluxML/NNlib.jl/issues/412

### CODE REVIEW

**Comment by ericphanson** [comment]
I think the registry will also have to be edited to retroactively add this upper bound to previous releases of NNlibCUDA. Otherwise the package resolver will just avoid the latest NNlibCUDA (due to this declared incompatibility) and resolve to older versions (which do not have declared incompatibility but are still incompatible in practice, IIUC). This can be done by a manual PR to General like https://github.com/JuliaRegistries/General/pull/53824

**Comment by mcabbott** [comment]
With this PR alone, the resolver will have to choose between avoiding latest NNlibCUDA (bad) and avoiding latest NNlib (good). Is that worth doing (better than the state right now?) or simpler to only make the registry edit?

**Comment by CarloLucibello** [comment]
thanks for the suggestion @ericphanson. So this PR can be closed and we just need https://github.com/JuliaRegistries/General/pull/61385/files?

**Comment by maxfreu** [comment]
I think with https://github.com/FluxML/NNlib.jl/pull/414 merged this can be closed. 8.6 has been yanked, so there shouldn't be any further version incompatibility problems.

**Pull request closed without merging**
