### PR TITLE
Missing Identity Activation Import

### PR DESCRIPTION
**Pull request by avik-pal**

### CODE REVIEW

**Review by ToucheSir — COMMENTED** [review]
Does this address some new error? Trying to understand why the seemingly unused import is necessary.

**Comment by avik-pal** [comment]
conv_bias_act uses it without the import

**Comment by ToucheSir** [comment]
Seems like we should add some regression testing for that, because CI isn't catching it.

**Review by ToucheSir — APPROVED** [review]

**Comment by avik-pal** [comment]
Oops, this had fallen off my radar. But added the tests. Also, where do the `rrule`s for the functions go. `conv_bias_act` pullback is erroring out as of now.

cc @ToucheSir

**Comment by DhairyaLGandhi** [comment]
The defs are at the end in conv.jl. we can reuse those `rrule`s for `conv_bias_act`. Does CUDNN have corresponding reverse passes?

**Comment by ToucheSir** [comment]
There shouldn't be a need to add any rrules to this repo, but we would need to add one to NNlib itself. Maybe revive [this part of https://github.com/FluxML/NNlib.jl/pull/346](https://github.com/FluxML/NNlib.jl/pull/346/files#diff-388e4608971ac56c9d65322911479604ece822401fa497bb34b51240d6abeb5fR46-R75).

**Comment by DhairyaLGandhi** [comment]
Maybe also remove https://github.com/FluxML/NNlibCUDA.jl/blob/e16e235f2863d9ea8401844a99e6fba7a3bc4e0f/src/cudnn/activations.jl#L38

It causes invalidations anyway

```Julia
inserting broadcasted(::typeof(identity), x::CUDA.CuArray{T}) where T<:Union{Float16, Float32, Float64} in NNlibCUDA at /home/dhairyalgandhi/.julia/packages/NNlibCUDA/i1IW9/src/cudnn/activations.jl:38 invalidated:
   backedges: 1: superseding broadcasted(f, arg1, args...) in Base.Broadcast at broadcast.jl:1294 with MethodInstance for Base.Broadcast.broadcasted(::typeof(identity), ::Any) (1 children)

```

**Comment by ToucheSir** [comment]
@avik-pal care to rebase this so we can get it in?

**Review by ToucheSir — COMMENTED** [review]
1.7 buildkite failure looks completely unrelated and probably signals we need to update our CI config. Since 1.6 is good and this change is super innocuous, I think it's good to merge.

**Review by ToucheSir — APPROVED** [review]

**Pull request merged**
