### PR TITLE
Replace workspace macro with do-block

### PR DESCRIPTION
**Pull request by akashkgarg**
This fixes the break introduced in CUDA.jl commit:
c77e98549a33b770017ea9cc09b950a7f47d3ab7

### CODE REVIEW

**Comment by devmotion** [comment]
This PR is needed for CUDA 3.3.1 it seems.

**Comment by DhairyaLGandhi** [comment]
LGTM, thanks

**Comment by maleadt** [comment]
LGTM, although it would be better to rebuild this on top of the new CUDNN wrappers in CUDA.jl.

**Comment by DhairyaLGandhi** [comment]
Agree, but that can happen in a separate pr, for now it's alright to merge this, so I'll do that and start a rewrite.

**Pull request merged**
