### PR TITLE
Add CUDA kernels for grid sampling

### PR DESCRIPTION
**Pull request by pxl-th**
GPU part for the [NNlib grid sampling PR](https://github.com/FluxML/NNlib.jl/pull/361).

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
Very cool! Thanks! Could we perhaps make the regular sampling code work with CuArrays directly?

**Comment by pxl-th** [comment]
Thanks, @DhairyaLGandhi. Can you, please, clarify, what is regular sampling? Do you mean something like this?

```julia
x = CuArray(...)
sampled = x[grid]
```

**Comment by pxl-th** [comment]
I guess you mean NNlib grid sampling code :)

**Comment by pxl-th** [comment]
Probably makes sense. I can make a separate function that accepts indices for the WHN dimensions, and then we can reuse it here.

**Comment by pxl-th** [comment]
The code is now re-using almost everything from the NNlib, except for the `_safe_add!` function which needs to do atomic addition and CUDA kernel indexing stuff.

**Review by CarloLucibello — APPROVED** [review]

**Pull request merged**
