### PR TITLE
introduce trilinear upsampling

### PR DESCRIPTION
**Pull request by maxfreu**
Hi! This is the counterpart to https://github.com/FluxML/NNlib.jl/pull/315 The checks fail because the NNlib PR is not yet merged.

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
We should also discuss supporting interpolations.jl directly. They have added the plumbing required to make it compatible with zygote. We would still need to support getting the adjoints to the Interpolations themselves, but this is a promising move nonetheless.

**Comment by maxfreu** [comment]
Maybe you can re-trigger the checks, as the corresponding NNlib PR has been merged.

**Comment by maxfreu** [comment]
@CarloLucibello @DhairyaLGandhi
I know it's not the best code in history, but I think after re-running the checks this is mergeable.

**Comment by CarloLucibello** [comment]
@maxfreu buildkite's error looks real:
```
 LoadError: LoadError: UndefVarError: upsample_trilinear_whdcn! not defined
```

**Comment by maxfreu** [comment]
Yes, that’s due to the separation of the packages and me forgetting to point the manifest to master. But now the summer has come, infections are down and so are the commits :D Will do it soon :) Also I still have the GPU version in the backlog.

**Comment by maxfreu** [comment]
I made some git chaos. Will make a new PR.

**Pull request closed without merging**
